[".vim/pack/tpope/start/vim-sensible"]
    type = "git-repo"
    url = "https://github.com/tpope/vim-sensible.git"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/AstroNvim/AstroNvim"
    [".config/nvim".pull]
        args = ["--depth", "1"]

